#!/bin/sh

echo "${GREEN}Starting Spotify Connect"

/usr/local/sbin/librespot -n "Enclume" -b 320 \
-c /tmp/spoticache --cache-size-limit 100M \
--backend alsa --enable-volume-normalisation --initial-volume 30 \
--device-type speaker --autoplay

# 2>&1 >> /var/log/librespot.log